# Generated by Django 2.0.6 on 2018-08-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(to='post.Tag', verbose_name='TEGI'),
        ),
    ]
