# Generated by Django 2.0.6 on 2018-08-02 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0002_news_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Com',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='KOMENT')),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={},
        ),
        migrations.AlterField(
            model_name='news',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='KOGDA_sozd'),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.CharField(max_length=100, verbose_name='opisanie'),
        ),
        migrations.AlterField(
            model_name='news',
            name='keywords',
            field=models.CharField(max_length=50, verbose_name='KLU4eBIE_SLOBA'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(verbose_name='TUT_POLNII_text_STATI'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text_min',
            field=models.TextField(max_length=400, verbose_name='malenkii_text'),
        ),
        migrations.AddField(
            model_name='com',
            name='new',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.News', verbose_name='Koment'),
        ),
        migrations.AddField(
            model_name='com',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="PolsoBatel'"),
        ),
    ]
