# Generated by Django 2.0.6 on 2018-08-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20180802_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='com',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data'),
        ),
        migrations.AddField(
            model_name='com',
            name='moder',
            field=models.BooleanField(default=False),
        ),
    ]
