# Generated by Django 2.0.6 on 2018-08-03 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20180802_2340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='com',
            options={'verbose_name': 'Koment', 'verbose_name_plural': 'Komenti'},
        ),
    ]
